services:
  - type: web
    name: kit-librarian-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        # Set this in the Render dashboard after creating the service
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CLIENT_ORIGIN
        # Update this to your actual frontend URL after the static site is deployed
        value: https://kit-librarian.onrender.com

  - type: static
    name: kit-librarian
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: build
    envVars:
      - key: REACT_APP_API_URL
        # Set this to the backend URL after the backend is deployed
        sync: false
      - key: NODE_ENV
        value: production
      - key: GENERATE_SOURCEMAP
        value: "false"
